apiVersion: batch/v1
kind: CronJob
metadata:
  name: flask-cleanup
  namespace: flask-app
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cleanup
              image: busybox
              command:
                - sh
                - -c
                - rm -rf /tmp/*
          restartPolicy: Never
