apiVersion: batch/v1
kind: CronJob
metadata:
  name: flask-healthcheck
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: healthcheck
              image: busybox
              command:
                - sh
                - -c
                - |
                  RESPONSE=$(wget -qO- http://flask-service/);
                  if echo "$RESPONSE" | grep -q "Hello, Doron!"; then
                    echo "Healthcheck passed";
                  else
                    echo "Healthcheck failed: $RESPONSE";
                    exit 1;
                  fi
          restartPolicy: Never
