apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  FLASK_DEBUG: {{ .Values.config.flaskDebug | quote }}
  APP_NAME: {{ .Values.config.appName | quote }}
  APP_VERSION: {{ .Values.config.appVersion | quote }}
